{{ config(materialized='table', transient=false, cluster_by=['CUSTOMER_ID']) }}

{{ config(query_tag = 'test_run_day_1') }}

WITH 
CUSTOMERS AS 
(

    SELECT *
    FROM {{ ref('stg_customers') }}

),

ORDERS AS (

    SELECT * 
    FROM {{ ref('stg_orders') }}

),

PAYMENTS AS (

    SELECT * 
    FROM {{ ref('stg_payments') }}
    WHERE STATUS = 'SUCCESS'
),



CUSTOMER_ORDERS AS (

    SELECT ORDERS.CUSTOMER_ID
         , MIN(ORDERS.ORDER_DATE) AS FIRST_ORDER_DATE
         , MAX(ORDERS.ORDER_DATE) AS MOST_RECENT_ORDER_DATE
         , COUNT(ORDERS.ORDER_ID) AS NUMBER_OF_ORDERS
         , SUM(PAYMENTS.AMOUNT) AS LIFETIME_AMMOUNT
    FROM ORDERS 
    LEFT
    JOIN PAYMENTS ON ORDERS.ORDER_ID = PAYMENTS.ORDER_ID 
    GROUP BY 1

),


FINAL AS (

    SELECT CUSTOMERS.CUSTOMER_ID
         , CUSTOMERS.FIRST_NAME
         , CUSTOMERS.LAST_NAME
         , CUSTOMER_ORDERS.FIRST_ORDER_DATE
         , CUSTOMER_ORDERS.MOST_RECENT_ORDER_DATE
         , COALESCE(CUSTOMER_ORDERS.NUMBER_OF_ORDERS, 0) AS NUMBER_OF_ORDERS
         , COALESCE(CUSTOMER_ORDERS.LIFETIME_AMMOUNT, 0) AS LIFETIME_AMMOUNT
    FROM CUSTOMERS
    LEFT 
    JOIN CUSTOMER_ORDERS ON CUSTOMERS.CUSTOMER_ID = CUSTOMER_ORDERS.CUSTOMER_ID

)

SELECT * FROM FINAL