version: 2

sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: orders
      - name: customers

  - name: stripe
    database: raw
    schema: stripe
    freshness: # default freshness
      warn_after: {count: 1, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _BATCHED_AT
    tables:
      - name: payment
        columns:
          - name: STATUS
            tests:
              - accepted_values:
                  values: ['success', 'fail']